const projects = [
  {
    id: 1,
    name: 'Stellar Brand Design',
    year: '2025',
    techStack: ['Next.js', 'GSAP', 'Sanity', 'Matter.js'],
    image: '/sbd.png',
    link: 'https://www.stellarbranddesign.com/',
  },
  {
    id: 2,
    name: 'Polatify',
    year: '2022',
    techStack: ['Vue.js', 'Express', 'Tailwind CSS', 'Spotify API'],
    image: '/polatify.png',
    link: 'https://polatify.netlify.app/',
  },
  {
    id: 3,
    name: 'Gedung Sate Interactive Map',
    year: '2024',
    techStack: ['Three.js', 'CSS'],
    image: '/gedung-sate.png',
    link: 'https://gedung-sate.netlify.app/',
  },
  {
    id: 4,
    name: 'Twice World',
    year: '2024',
    techStack: ['Next.js', 'Tailwind CSS', 'Firebase'],
    image: '/twiceland.png',
    link: 'https://twice-world.netlify.app/',
  },
  {
    id: 5,
    name: 'Cinefo',
    year: '2022',
    techStack: ['Vue.js', 'Tailwind CSS', 'The Movie Database API'],
    image: '/cinefo.png',
    link: 'https://cinefo.netlify.app/',
  },
  {
    id: 6,
    name: 'Celestara',
    year: '2025',
    techStack: ['Next.js', 'Tailwind CSS', 'GSAP', 'Three.js'],
    image: '/celestara.png',
    link: 'https://celestarafest.netlify.app/',
  },
  {
    id: 7,
    name: 'Komplek',
    year: '2025',
    techStack: ['React.js', 'Tailwind CSS'],
    image: '/komplek.png',
    link: 'https://komplek.netlify.app/',
  },
  {
    id: 8,
    name: 'This is Indonesia',
    year: '2022',
    techStack: ['React.js', 'Tailwind CSS'],
    image: '/this-is-indonesia.png',
    link: 'https://thisisindonesia.netlify.app/',
  },
  {
    id: 9,
    name: 'Personal Website V2',
    year: '2022',
    techStack: ['React.js', 'Styled Components', 'Three.js'],
    image: '/personal-website-v2.png',
    link: 'https://fikrialbaihaqi.netlify.app/',
  },
  {
    id: 10,
    name: 'Whats the weather at?',
    year: '2022',
    techStack: ['Vue.js', 'Tailwind CSS', 'OpenWeatherMap API'],
    image: '/weather-app.png',
    link: 'https://whatstheweatherat.netlify.app/',
  },
  {
    id: 11,
    name: 'Newsthetic',
    year: '2022',
    techStack: ['React.js', 'Tailwind CSS', 'News API'],
    image: '/newsthetic.png',
    link: 'https://github.com/fikri-albaihaqi/newsthetic',
  },
  {
    id: 12,
    name: 'Jaya Tirta',
    year: '2022',
    techStack: ['Flutter', 'Python', 'Fast API', 'Firebase'],
    image: '/jaya-tirta.png',
    link: '',
  },
]

export default projects
